
services:
  - type: web
    name: notes-app-sbcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: notes-db
    plan: free
    databaseName: notes_db
    user: notes_user
